version: "3.7"

services:
  backend:
    build: backend/
    image: ecommerce-backend-img
    container_name: ecommerce-backend-cont
    ports:
      - "8080:8080"
    environment:
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "${BACKEND_HEALTHCHECK_CMD}"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        # Send backend URL as argument to Dockerfile
        - VITE_API_BASE_URL=${BACKEND_PRODUCTS_URL}
    image: ecommerce-client-img
    container_name: ecommerce-frontend-cont
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy

  database:
    image: mariadb:11.0
    container_name: ecommerce-mariadb
    ports:
      - "3306:3306"
    healthcheck:
      test: ${DB_HEALTHCHECK_CMD}
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
